### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by atareshawty** [osumb/challenges#1]
## Development
- [x] Figure out hosting
- [x] Testing framework
- [x] CI
- [x] Easy deployments (through whatever hosting is chosen)

## Features
- [x] Data Models/Database setup
- [x] Consistent URL structure

**Comment by atareshawty** [comment]
This checklist is for major features/development steps/etc to keep track of where the project is and what needs done

**Comment by atareshawty** [comment]
For now, Heroku will be the hosting solution (for now)

**Comment by atareshawty** [comment]
https://github.com/osumb/challenges/pull/3 (CI/hosting)

**Comment by atareshawty** [comment]
https://github.com/osumb/challenges/pull/6 => As start for testing

**Comment by atareshawty** [comment]
This list is basically done and useless to me now
