### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by atareshawty** [osumb/challenges#78]
These are the things that for sure need to get done to be usable:

- [x] Email user when he/she signs up for challenge
- [x] Spot switch when challenge result is confirmed
- [x] Challenge list exporting when signup time is over ([Node-Schedule](https://github.com/node-schedule/node-schedule) when a performance is created)
- [x] Logging on challenge success (for my sanity and debugging)
- [x] #87
- [x] Admin things that would be useful to have (probably need to meet with Tess)
- [x] #114 
- [x] #110
- [x] Just learned today that different directors are going to be responsible for approving different instrument groups so there are some permission things that need to get built
- [x] #108
- [x] #126 
- [x] Styling
- [x] #125 (~~@tarebyte~~)
- [x] Automated Testing of the entire process
- [x] #156 
- [x] Finish all `TODO:`'s in the code
- [x] #164 
- [x] Sockets - to remove a person from the list if they've been challenged while a user is on the page (not high priority. Probably shouldn't mess since release is soon)

**Comment by atareshawty** [comment]
This will probably need to be edited as things continue

**Comment by atareshawty** [comment]
#87 Has to be a part of this

**Comment by atareshawty** [comment]
I'm checking off admin things because of #106

**Comment by atareshawty** [comment]
I checked off `TODOs` because of #157 . It took care of the last one 🎉

**Comment by atareshawty** [comment]
This was a pre-release checklist. We've released. Moving sockets to a separate issue and closing this one
